(function(){var $=function(i){return document.getElementById(i)},R=matchMedia('(prefers-reduced-motion:reduce)').matches,w=function(t){return new Promise(function(r){setTimeout(r,t)})};
var m=$('m'),n=$('nv');m.onclick=function(){var o=n.classList.toggle('o');m.setAttribute('aria-expanded',o);m.textContent=o?'Close':'Menu'};n.onclick=function(e){if(e.target.tagName=='A')n.classList.remove('o')};
var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add('on');io.unobserve(e.target)}})},{threshold:.15});document.querySelectorAll('.rv').forEach(function(e){io.observe(e)});
var ms=$('ms'),mb=$('mb'),cur=ms.textContent;function say(t){if(!t||t==cur)return;cur=t;mb.classList.add('sw');setTimeout(function(){ms.textContent=t;mb.classList.remove('sw')},400)}
var so=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting)say(e.target.dataset.say)})},{threshold:.5});document.querySelectorAll('[data-say]').forEach(function(e){if(e.tagName!='BODY')so.observe(e)});
document.querySelectorAll('.lg').forEach(function(c){c.onclick=function(){c.classList.toggle('on')}});
var dg=$('dg');if(dg){document.querySelectorAll('.bc').forEach(function(c){c.onclick=function(){dg.querySelector('img').src='assets/'+c.dataset.i+'.jpg';dg.querySelector('img').alt=c.dataset.t;dg.querySelector('h3').textContent=c.dataset.t;dg.querySelector('p').textContent=c.dataset.d;dg.querySelector('.bt').href=c.dataset.l;dg.showModal()}});dg.querySelector('.x').onclick=function(){dg.close()};dg.onclick=function(e){if(e.target==dg)dg.close()}}
var ac,tm,on=!1,N=[261.63,293.66,329.63,392,440,523.25,587.33,659.25],sd=$('sd');
function nt(){var t=ac.currentTime,f=N[Math.random()*N.length|0];[[f,.05],[f*2.76,.012]].forEach(function(p){var o=ac.createOscillator(),g=ac.createGain();o.frequency.value=p[0];g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(p[1],t+.01);g.gain.exponentialRampToValueAtTime(1e-4,t+1.8);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+1.9)});tm=setTimeout(nt,1300+Math.random()*2300)}
sd.onclick=function(){on=!on;sd.setAttribute('aria-pressed',on);if(on){ac=ac||new(window.AudioContext||window.webkitAudioContext)();ac.resume();nt()}else clearTimeout(tm)};
var nm=$('nm');if(nm){var lc=$('lc'),qa=$('qa'),qr=$('qr'),q=$('q'),done=!1,
roles=['Biomedical Engineer','Entrepreneur','Business Person','Woman in STEM','Educationist','Game Developer','Mentor','Educator','Free Soul','Cat Person :)'];
var fin=function(){if(done)return;done=!0;nm.hidden=q.hidden=!0;lc.classList.add('on')};
var ty=async function(el,s){el.textContent='';for(var i=1;i<=s.length&&!done;i++){el.textContent=s.slice(0,i);await w(55)}};
if(R){fin()}else{addEventListener('scroll',function(){if(scrollY>60)fin()},{passive:!0});(async function(){await w(3000);nm.classList.add('out');await w(900);nm.hidden=!0;await ty(qa,'Are you a');await w(400);for(var i=0;i<roles.length&&!done;i++){await ty(qr,roles[i]);await w(3000)}if(!done){q.style.transition='opacity .8s';q.style.opacity=0;await w(900);fin()}})()}}})();
document.querySelectorAll('.yv').forEach(function(b){b.onclick=function(){var f=document.createElement('iframe');f.src='https://www.youtube-nocookie.com/embed/'+b.dataset.id+'?autoplay=1&rel=0';f.allow='autoplay;encrypted-media;picture-in-picture;fullscreen';f.allowFullscreen=true;f.title=b.dataset.t;b.parentNode.replaceChild(f,b)}});
